import type { CatalogProduct } from "~/types/landing";

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  // ─── Đồng Hồ ──────────────────────────────────────────
  {
    id: "p-watch-01",
    slug: "seiko-presage-cocktail",
    name: "Seiko Presage Cocktail Time",
    brand: "Seiko",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 4500000,
    salePrice: 3990000,
    icon: "watch",
    images: [
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Mặt số enamel gradient xanh lam, bộ máy 4R35 automatic, kính Hardlex cong, dây da bê Italy.",
    specs: [
      { label: "Bộ máy", value: "4R35 Automatic" },
      { label: "Chống nước", value: "5ATM" },
      { label: "Đường kính", value: "40.5mm" },
      { label: "Dây", value: "Da bê Italy" },
    ],
    tags: ["automatic", "dress-watch"],
    rating: 4.8,
    reviewCount: 124,
    stock: 15,
    isBestSeller: true,
  },
  {
    id: "p-watch-02",
    slug: "fossil-grant-chrono",
    name: "Fossil Grant Chronograph",
    brand: "Fossil",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 3200000,
    icon: "watch",
    images: [
      "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Mặt kem vintage, 3 subdial, vỏ thép rose gold, dây da nâu cognac. Chronograph quartz chính xác.",
    specs: [
      { label: "Bộ máy", value: "Quartz Chrono" },
      { label: "Chống nước", value: "5ATM" },
      { label: "Đường kính", value: "44mm" },
      { label: "Dây", value: "Da bò" },
    ],
    tags: ["chronograph", "vintage"],
    rating: 4.5,
    reviewCount: 89,
    stock: 22,
    isNew: true,
  },
  {
    id: "p-watch-03",
    slug: "orient-bambino-v2",
    name: "Orient Bambino Version 2",
    brand: "Orient",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 3800000,
    icon: "watch",
    images: [
      "https://images.unsplash.com/photo-1587925358603-c2eea5305bbc?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Thiết kế Bauhaus tối giản, bộ máy F6722 in-house, mặt trắng ngà, kim cathedral.",
    specs: [
      { label: "Bộ máy", value: "F6722 Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "40.5mm" },
      { label: "Kính", value: "Mineral domed" },
    ],
    tags: ["automatic", "bauhaus"],
    rating: 4.7,
    reviewCount: 203,
    stock: 8,
    isLuxury: true,
  },
  {
    id: "p-watch-04",
    slug: "casio-edifice-efv",
    name: "Casio Edifice EFV-540D",
    brand: "Casio",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 2600000,
    icon: "watch",
    images: [
      "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Thiết kế sportive, vỏ thép bạc, mặt đen carbon texture, kim dạ quang Neobrite.",
    specs: [
      { label: "Bộ máy", value: "Quartz" },
      { label: "Chống nước", value: "10ATM" },
      { label: "Đường kính", value: "43.3mm" },
      { label: "Dây", value: "Thép 316L" },
    ],
    tags: ["sporty", "steel"],
    rating: 4.4,
    reviewCount: 67,
    stock: 30,
  },
  {
    id: "p-watch-05",
    slug: "citizen-eco-drive",
    name: "Citizen Eco-Drive AW1573",
    brand: "Citizen",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 5200000,
    icon: "watch",
    images: [
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Bộ máy Eco-Drive năng lượng ánh sáng, mặt xanh navy gradient, vỏ thép bọc PVD gold.",
    specs: [
      { label: "Bộ máy", value: "Eco-Drive Solar" },
      { label: "Chống nước", value: "10ATM" },
      { label: "Đường kính", value: "41mm" },
      { label: "Trữ năng lượng", value: "180 ngày" },
    ],
    tags: ["eco-drive", "solar"],
    rating: 4.6,
    reviewCount: 152,
    stock: 12,
    isLuxury: true,
  },
  {
    id: "p-watch-06",
    slug: "tissot-prx-powermatic",
    name: "Tissot PRX Powermatic 80",
    brand: "Tissot",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 12500000,
    icon: "watch",
    images: [
      "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Vỏ integated bracelet phong cách thập niên 70, Powermatic 80 trữ cót 80 giờ, mặt waffle xanh lá.",
    specs: [
      { label: "Bộ máy", value: "Powermatic 80" },
      { label: "Chống nước", value: "10ATM" },
      { label: "Đường kính", value: "40mm" },
      { label: "Trữ cót", value: "80 giờ" },
    ],
    tags: ["automatic", "luxury", "swiss"],
    rating: 4.9,
    reviewCount: 78,
    stock: 5,
    isLuxury: true,
    isBestSeller: true,
  },

  // ─── Zippo ─────────────────────────────────────────────
  {
    id: "p-zippo-01",
    slug: "zippo-black-ice",
    name: "Zippo Black Ice 150",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 650000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/1200x/72/b8/f7/72b8f76799dc6e82f50b09aa91e69cdf.jpg",
    ],
    description:
      "Lớp phủ Black Ice phản chiếu bóng loáng như gương đen. Khắc tên laser miễn phí.",
    specs: [
      { label: "Chất liệu", value: "Đồng thau mạ PVD" },
      { label: "Kích thước", value: "56×36×12mm" },
      { label: "Xuất xứ", value: "Bradford, PA, USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["classic", "black"],
    rating: 4.7,
    reviewCount: 312,
    stock: 45,
    isBestSeller: true,
  },
  {
    id: "p-zippo-02",
    slug: "zippo-armor-deep-carve",
    name: "Zippo Armor Deep Carve",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 1350000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/736x/0f/49/d2/0f49d26cfb9f2240619adb8814872fca.jpg",
    ],
    description:
      "Vỏ Armor dày 1.5x, khắc chìm 360° hoa văn Celtic. Mạ antique brass.",
    specs: [
      { label: "Chất liệu", value: "Đồng Armor 1.5x" },
      { label: "Kỹ thuật", value: "Deep carve 360°" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["armor", "limited"],
    rating: 4.9,
    reviewCount: 56,
    stock: 8,
    isLuxury: true,
  },
  {
    id: "p-zippo-03",
    slug: "zippo-venetian-brass",
    name: "Zippo Venetian High Polish Brass",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 780000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/webp80/736x/8c/0f/92/8c0f92c1ff7913f0899678c2d212fe17.webp",
    ],
    description:
      "Họa tiết Venetian cổ điển khắc hai mặt, đồng thau bóng cao. Biểu tượng Zippo vượt thời gian.",
    specs: [
      { label: "Chất liệu", value: "Đồng thau bóng" },
      { label: "Họa tiết", value: "Venetian hai mặt" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["vintage", "brass"],
    rating: 4.6,
    reviewCount: 98,
    stock: 25,
  },
  {
    id: "p-zippo-04",
    slug: "zippo-matte-navy",
    name: "Zippo Navy Matte 239",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 550000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/736x/ba/60/3f/ba603fc7eeb31b65c935eb6b35cc6e19.jpg",
    ],
    description:
      "Bề mặt sơn matte xanh navy trầm lắng. Mặc định cho gentleman — không phô trương, đủ tinh tế.",
    specs: [
      { label: "Chất liệu", value: "Thép sơn matte" },
      { label: "Màu", value: "Navy #239" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["matte", "everyday"],
    rating: 4.3,
    reviewCount: 145,
    stock: 60,
    isNew: true,
  },
  {
    id: "p-zippo-05",
    slug: "zippo-replica-1941",
    name: "Zippo 1941 Replica Brushed Chrome",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 890000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/736x/34/33/39/343339fcf3e40d20097689d1d81281bb.jpg",
    ],
    description:
      "Phiên bản tái hiện mẫu 1941 — góc bo tròn, bản lề 4 trục, vỏ thép chrome brushed.",
    specs: [
      { label: "Chất liệu", value: "Thép chrome" },
      { label: "Dòng", value: "1941 Replica" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["replica", "heritage"],
    rating: 4.8,
    reviewCount: 76,
    stock: 14,
    isLuxury: true,
  },
  {
    id: "p-zippo-06",
    slug: "zippo-jack-daniels",
    name: "Zippo Jack Daniel's Old No. 7",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 950000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/736x/3d/ea/57/3dea57bf61d87893f4cca0aa535faf34.jpg",
    ],
    description:
      "Phiên bản hợp tác Jack Daniel's, khắc logo nổi trên nền thép đen matte.",
    specs: [
      { label: "Chất liệu", value: "Thép đen matte" },
      { label: "Phiên bản", value: "Jack Daniel's collab" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["collab", "limited"],
    rating: 4.7,
    reviewCount: 42,
    stock: 10,
    isBestSeller: true,
  },

  // ─── Kính Mắt ──────────────────────────────────────────
  {
    id: "p-glasses-01",
    slug: "rayban-aviator-classic",
    name: "Ray-Ban Aviator Classic RB3025",
    brand: "Ray-Ban",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 2200000,
    icon: "glasses",
    images: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Biểu tượng phi công từ 1937. Gọng vàng, tròng G-15 xanh lá. UV400, phân cực.",
    specs: [
      { label: "Gọng", value: "Kim loại vàng" },
      { label: "Tròng", value: "G-15 phân cực" },
      { label: "Chống", value: "UV400" },
      { label: "Kích cỡ", value: "58mm" },
    ],
    tags: ["aviator", "iconic"],
    rating: 4.8,
    reviewCount: 287,
    stock: 35,
    isBestSeller: true,
  },
  {
    id: "p-glasses-02",
    slug: "persol-po0649",
    name: "Persol PO0649 Steve McQueen",
    brand: "Persol",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 4800000,
    icon: "glasses",
    images: [
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Thiết kế Italy, bản lề Meflecto linh hoạt, acetate tortoise shell, tròng crystal green.",
    specs: [
      { label: "Gọng", value: "Acetate Havana" },
      { label: "Bản lề", value: "Meflecto" },
      { label: "Tròng", value: "Crystal green" },
      { label: "Xuất xứ", value: "Italy" },
    ],
    tags: ["luxury", "italian"],
    rating: 4.9,
    reviewCount: 63,
    stock: 7,
    isLuxury: true,
  },
  {
    id: "p-glasses-03",
    slug: "hugo-boss-1199s",
    name: "Hugo Boss 1199/S",
    brand: "Hugo Boss",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 3100000,
    icon: "glasses",
    images: [],
    description:
      "Gọng titanium siêu nhẹ, mặt vuông nam tính, tròng gradient smoke. Phong cách doanh nhân.",
    specs: [
      { label: "Gọng", value: "Titanium matte" },
      { label: "Tròng", value: "Gradient smoke" },
      { label: "Trọng lượng", value: "22g" },
      { label: "Kích cỡ", value: "56mm" },
    ],
    tags: ["business", "titanium"],
    rating: 4.5,
    reviewCount: 41,
    stock: 18,
    isNew: true,
  },
  {
    id: "p-glasses-04",
    slug: "oakley-holbrook",
    name: "Oakley Holbrook OO9102",
    brand: "Oakley",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 2800000,
    icon: "glasses",
    images: [],
    description:
      "O Matter frame bền nhẹ, tròng Prizm tương phản cao. Casual, thể thao, sáng tối đều đẹp.",
    specs: [
      { label: "Gọng", value: "O Matter" },
      { label: "Tròng", value: "Prizm Black" },
      { label: "Chống", value: "UV400" },
      { label: "Kích cỡ", value: "55mm" },
    ],
    tags: ["sporty", "prizm"],
    rating: 4.6,
    reviewCount: 178,
    stock: 28,
  },
  {
    id: "p-glasses-05",
    slug: "montblanc-mb0263s",
    name: "Mont Blanc MB0263S",
    brand: "Mont Blanc",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 7200000,
    icon: "glasses",
    images: [],
    description:
      "Logo snowcap trên gọng vàng hồng, acetate đen bóng, tròng xám chống lóa. Đẳng cấp thượng lưu.",
    specs: [
      { label: "Gọng", value: "Acetate + kim loại rose gold" },
      { label: "Tròng", value: "Xám polarized" },
      { label: "Xuất xứ", value: "Italy" },
      { label: "Kích cỡ", value: "54mm" },
    ],
    tags: ["luxury", "business"],
    rating: 4.9,
    reviewCount: 22,
    stock: 4,
    isLuxury: true,
  },
  {
    id: "p-glasses-06",
    slug: "rayban-wayfarer",
    name: "Ray-Ban Original Wayfarer RB2140",
    brand: "Ray-Ban",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 2500000,
    icon: "glasses",
    images: [],
    description:
      "Huyền thoại từ 1956. Acetate đen, tròng G-15. Không bao giờ lỗi mốt.",
    specs: [
      { label: "Gọng", value: "Acetate đen" },
      { label: "Tròng", value: "G-15" },
      { label: "Chống", value: "UV400" },
      { label: "Kích cỡ", value: "50mm" },
    ],
    tags: ["wayfarer", "iconic"],
    rating: 4.7,
    reviewCount: 345,
    stock: 40,
  },

  // ─── Thắt Lưng ─────────────────────────────────────────
  {
    id: "p-belt-01",
    slug: "da-bo-fullgrain-italy",
    name: "Thắt Lưng Da Bò Full-grain Italy",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 480000,
    icon: "belt",
    images: [
      "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Da bò full-grain nhập Italy, khoá kim inox không rỉ, đường may chỉ sáp tay.",
    specs: [
      { label: "Chất liệu", value: "Da bò full-grain" },
      { label: "Khoá", value: "Inox 316L" },
      { label: "Rộng", value: "35mm" },
      { label: "Xuất xứ da", value: "Italy" },
    ],
    tags: ["fullgrain", "classic"],
    rating: 4.6,
    reviewCount: 201,
    stock: 50,
    isBestSeller: true,
  },
  {
    id: "p-belt-02",
    slug: "that-lung-khoa-tu-dong",
    name: "Thắt Lưng Khoá Tự Động Nano",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 350000,
    icon: "belt",
    images: [],
    description:
      "Khoá tự động trượt êm, da bò top-grain, cắt size tại nhà dễ dàng.",
    specs: [
      { label: "Chất liệu", value: "Da bò top-grain" },
      { label: "Khoá", value: "Tự động nano" },
      { label: "Rộng", value: "35mm" },
      { label: "Dài", value: "Cắt được" },
    ],
    tags: ["auto-buckle", "everyday"],
    rating: 4.3,
    reviewCount: 156,
    stock: 80,
    isNew: true,
  },
  {
    id: "p-belt-03",
    slug: "that-lung-da-van-ca-sau",
    name: "Thắt Lưng Da Vân Cá Sấu",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 890000,
    icon: "belt",
    images: [],
    description:
      "Da bò dập vân cá sấu thật, khoá liền đồng thau cổ điển. Sang trọng, bền bỉ.",
    specs: [
      { label: "Chất liệu", value: "Da bò vân cá sấu" },
      { label: "Khoá", value: "Đồng thau antique" },
      { label: "Rộng", value: "35mm" },
      { label: "Bảo hành", value: "12 tháng" },
    ],
    tags: ["croc-embossed", "luxury"],
    rating: 4.7,
    reviewCount: 88,
    stock: 15,
    isLuxury: true,
  },
  {
    id: "p-belt-04",
    slug: "that-lung-hai-mat",
    name: "Thắt Lưng Hai Mặt Đen–Nâu",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 420000,
    icon: "belt",
    images: [],
    description:
      "Một chiếc thắt lưng, hai phong cách: mặt đen formal, mặt nâu casual. Khoá xoay 180°.",
    specs: [
      { label: "Chất liệu", value: "Da bò split" },
      { label: "Khoá", value: "Xoay 180°" },
      { label: "Rộng", value: "33mm" },
      { label: "Màu", value: "Đen / Nâu" },
    ],
    tags: ["reversible", "versatile"],
    rating: 4.4,
    reviewCount: 134,
    stock: 42,
  },
  {
    id: "p-belt-05",
    slug: "that-lung-braided",
    name: "Thắt Lưng Bện Tay Da Bò",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 560000,
    icon: "belt",
    images: [],
    description:
      "Bện thủ công 8 sợi da bò, co giãn linh hoạt, không cần lỗ, thoải mái cả ngày.",
    specs: [
      { label: "Chất liệu", value: "Da bò bện 8 sợi" },
      { label: "Khoá", value: "Inox bạc" },
      { label: "Rộng", value: "35mm" },
      { label: "Co giãn", value: "Có" },
    ],
    tags: ["braided", "casual"],
    rating: 4.5,
    reviewCount: 67,
    stock: 30,
  },
  {
    id: "p-belt-06",
    slug: "that-lung-montblanc-style",
    name: "Thắt Lưng Khoá Chữ M Premium",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 680000,
    icon: "belt",
    images: [],
    description:
      "Khoá chữ M mạ PVD gold, da Saffiano đen. Dòng cao cấp nhất của IRONMAN.",
    specs: [
      { label: "Chất liệu", value: "Da Saffiano" },
      { label: "Khoá", value: "PVD gold chữ M" },
      { label: "Rộng", value: "35mm" },
      { label: "Hộp", value: "Hộp gỗ + túi nhung" },
    ],
    tags: ["premium", "gift"],
    rating: 4.8,
    reviewCount: 53,
    stock: 12,
    isLuxury: true,
  },

  // ─── Ví Da ─────────────────────────────────────────────
  {
    id: "p-wallet-01",
    slug: "vi-bifold-italy",
    name: "Ví Bifold Da Bò Italy",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 850000,
    icon: "wallet",
    images: [
      "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Da bò Italy vegetable-tanned, 8 ngăn thẻ, 2 ngăn tiền, 1 ngăn zip. Lên patina đẹp theo thời gian.",
    specs: [
      { label: "Chất liệu", value: "Veg-tan Italy" },
      { label: "Ngăn thẻ", value: "8" },
      { label: "Kích thước", value: "11×9.5cm" },
      { label: "Màu", value: "Nâu cognac" },
    ],
    tags: ["bifold", "classic"],
    rating: 4.7,
    reviewCount: 189,
    stock: 35,
    isBestSeller: true,
  },
  {
    id: "p-wallet-02",
    slug: "vi-card-holder",
    name: "Card Holder Da Saffiano",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 350000,
    icon: "wallet",
    images: [],
    description:
      "6 ngăn thẻ, 1 ngăn giữa. Da Saffiano chống trầy, mỏng gọn bỏ túi trước.",
    specs: [
      { label: "Chất liệu", value: "Da Saffiano" },
      { label: "Ngăn thẻ", value: "6" },
      { label: "Kích thước", value: "10×7.5cm" },
      { label: "Độ dày", value: "7mm" },
    ],
    tags: ["card-holder", "slim"],
    rating: 4.5,
    reviewCount: 234,
    stock: 65,
    isNew: true,
  },
  {
    id: "p-wallet-03",
    slug: "vi-dai-da-bo",
    name: "Ví Dài Da Bò Zipper",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 980000,
    icon: "wallet",
    images: [],
    description:
      "Ví dài full-zip, 12 ngăn thẻ, 3 ngăn tiền, 1 ngăn phone. Da bò nappa mềm mịn.",
    specs: [
      { label: "Chất liệu", value: "Da nappa" },
      { label: "Ngăn thẻ", value: "12" },
      { label: "Kích thước", value: "20×10cm" },
      { label: "Khóa", value: "YKK zipper" },
    ],
    tags: ["long-wallet", "zipper"],
    rating: 4.6,
    reviewCount: 97,
    stock: 20,
    isLuxury: true,
  },
  {
    id: "p-wallet-04",
    slug: "vi-money-clip",
    name: "Money Clip Da + Thép",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 450000,
    icon: "wallet",
    images: [],
    description:
      "Kẹp tiền thép phay CNC, bọc da bò hai mặt. 4 ngăn thẻ. Mỏng chỉ 8mm.",
    specs: [
      { label: "Chất liệu", value: "Da bò + thép 316L" },
      { label: "Ngăn thẻ", value: "4" },
      { label: "Kích thước", value: "10.5×7.5cm" },
      { label: "Độ dày", value: "8mm" },
    ],
    tags: ["money-clip", "minimalist"],
    rating: 4.4,
    reviewCount: 78,
    stock: 38,
  },
  {
    id: "p-wallet-05",
    slug: "vi-passport-da",
    name: "Ví Passport Da Bò",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 520000,
    icon: "wallet",
    images: [],
    description:
      "Ngăn passport, 4 ngăn thẻ, ngăn boarding pass. Khắc tên miễn phí — quà đi du lịch lý tưởng.",
    specs: [
      { label: "Chất liệu", value: "Da bò full-grain" },
      { label: "Ngăn", value: "Passport + 4 thẻ" },
      { label: "Kích thước", value: "14×10cm" },
      { label: "Khắc tên", value: "Miễn phí" },
    ],
    tags: ["passport", "travel", "gift"],
    rating: 4.8,
    reviewCount: 112,
    stock: 25,
    isBestSeller: true,
  },
  {
    id: "p-wallet-06",
    slug: "vi-rfid-blocking",
    name: "Ví RFID Blocking Slim",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 620000,
    icon: "wallet",
    images: [],
    description:
      "Lớp chống RFID bảo vệ thẻ. Da carbon fiber texture, 6 ngăn thẻ, ngăn tiền mặt.",
    specs: [
      { label: "Chất liệu", value: "Da carbon texture" },
      { label: "RFID", value: "Blocking" },
      { label: "Ngăn thẻ", value: "6" },
      { label: "Độ dày", value: "10mm" },
    ],
    tags: ["rfid", "tech", "slim"],
    rating: 4.5,
    reviewCount: 89,
    stock: 30,
    isNew: true,
  },

  // ─── Mũ ────────────────────────────────────────────────
  {
    id: "p-hat-01",
    slug: "fedora-len-long-cuu",
    name: "Fedora Len Lông Cừu Classic",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 680000,
    icon: "hat",
    images: [
      "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Len lông cừu Úc, vành 7cm, băng grosgrain đen. Phong cách quý ông thập niên 40.",
    specs: [
      { label: "Chất liệu", value: "Len lông cừu 100%" },
      { label: "Vành", value: "7cm" },
      { label: "Size", value: "M/L/XL" },
      { label: "Màu", value: "Đen / Xám / Nâu" },
    ],
    tags: ["fedora", "classic", "wool"],
    rating: 4.7,
    reviewCount: 56,
    stock: 20,
    isBestSeller: true,
  },
  {
    id: "p-hat-02",
    slug: "flat-cap-tweed",
    name: "Flat Cap Tweed Harris",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 520000,
    icon: "hat",
    images: [
      "https://images.unsplash.com/photo-1588850561407-ed78c334e67a?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Vải tweed Harris Scotland, lót lụa, lưỡi trai cứng. Mũ beret Anh cổ điển.",
    specs: [
      { label: "Chất liệu", value: "Harris Tweed" },
      { label: "Lót", value: "Lụa" },
      { label: "Size", value: "M/L/XL" },
      { label: "Xuất xứ vải", value: "Scotland" },
    ],
    tags: ["flat-cap", "tweed", "british"],
    rating: 4.6,
    reviewCount: 43,
    stock: 18,
    isNew: true,
  },
  {
    id: "p-hat-03",
    slug: "beret-da-nappa",
    name: "Beret Da Nappa Đen",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 750000,
    icon: "hat",
    images: [],
    description:
      "Da nappa cừu mềm mịn, lót cotton thoáng, kiểu dáng beret Pháp. Sang trọng bốn mùa.",
    specs: [
      { label: "Chất liệu", value: "Da nappa cừu" },
      { label: "Lót", value: "Cotton" },
      { label: "Size", value: "M/L/XL" },
      { label: "Màu", value: "Đen" },
    ],
    tags: ["beret", "leather", "french"],
    rating: 4.8,
    reviewCount: 31,
    stock: 10,
    isLuxury: true,
  },
  {
    id: "p-hat-04",
    slug: "panama-coi-thu-cong",
    name: "Mũ Panama Cói Ecuador",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 1200000,
    icon: "hat",
    images: [],
    description:
      "Cói Toquilla bện thủ công tại Ecuador. Nhẹ, thoáng, gập được. Biểu tượng mùa hè quý ông.",
    specs: [
      { label: "Chất liệu", value: "Cói Toquilla" },
      { label: "Bện", value: "Thủ công" },
      { label: "Vành", value: "6.5cm" },
      { label: "Xuất xứ", value: "Ecuador" },
    ],
    tags: ["panama", "handmade", "summer"],
    rating: 4.9,
    reviewCount: 19,
    stock: 6,
    isLuxury: true,
  },
  {
    id: "p-hat-05",
    slug: "mu-newsboy-wool",
    name: "Newsboy Cap Wool Blend",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 450000,
    icon: "hat",
    images: [],
    description:
      "Mũ newsboy 8 múi, len pha, nút bọc trên đỉnh. Phong cách Peaky Blinders.",
    specs: [
      { label: "Chất liệu", value: "Len pha 80/20" },
      { label: "Kiểu", value: "8 múi" },
      { label: "Size", value: "M/L/XL" },
      { label: "Màu", value: "Xám đậm" },
    ],
    tags: ["newsboy", "peaky-blinders"],
    rating: 4.5,
    reviewCount: 67,
    stock: 25,
    isBestSeller: true,
  },
  {
    id: "p-hat-06",
    slug: "mu-bucket-da-lon",
    name: "Bucket Hat Da Lộn",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 580000,
    icon: "hat",
    images: [],
    description:
      "Da lộn (suede) mềm mại, vành ngắn 5cm, kiểu dáng bucket hiện đại. Casual sang trọng.",
    specs: [
      { label: "Chất liệu", value: "Da lộn (suede)" },
      { label: "Vành", value: "5cm" },
      { label: "Size", value: "M/L" },
      { label: "Màu", value: "Nâu camel" },
    ],
    tags: ["bucket", "suede", "casual"],
    rating: 4.4,
    reviewCount: 38,
    stock: 22,
    isNew: true,
  },
];

export const PRODUCT_BY_SLUG: Record<string, CatalogProduct> =
  Object.fromEntries(CATALOG_PRODUCTS.map((p) => [p.slug, p]));
