import type { CatalogProduct } from "~/types/landing";

/** Danh mục Thắt Lưng — 6 sản phẩm. */
export const BELT_PRODUCTS: CatalogProduct[] = [
  {
    id: "p-belt-01",
    slug: "da-bo-fullgrain-italy",
    name: "Thắt Lưng Da Bò Full-grain Italy",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 480000,
    icon: "belt",
    images: [
      "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Da bò full-grain nhập Italy, khoá kim inox không rỉ, đường may chỉ sáp tay.",
    specs: [
      { label: "Chất liệu", value: "Da bò full-grain" },
      { label: "Khoá", value: "Inox 316L" },
      { label: "Rộng", value: "35mm" },
      { label: "Xuất xứ da", value: "Italy" },
    ],
    tags: ["fullgrain", "classic"],
    rating: 4.6,
    reviewCount: 201,
    stock: 50,
    isBestSeller: true,
  },
  {
    id: "p-belt-02",
    slug: "that-lung-khoa-tu-dong",
    name: "Thắt Lưng Khoá Tự Động Nano",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 350000,
    icon: "belt",
    images: [],
    description:
      "Khoá tự động trượt êm, da bò top-grain, cắt size tại nhà dễ dàng.",
    specs: [
      { label: "Chất liệu", value: "Da bò top-grain" },
      { label: "Khoá", value: "Tự động nano" },
      { label: "Rộng", value: "35mm" },
      { label: "Dài", value: "Cắt được" },
    ],
    tags: ["auto-buckle", "everyday"],
    rating: 4.3,
    reviewCount: 156,
    stock: 80,
    isNew: true,
  },
  {
    id: "p-belt-03",
    slug: "that-lung-da-van-ca-sau",
    name: "Thắt Lưng Da Vân Cá Sấu",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 890000,
    icon: "belt",
    images: [],
    description:
      "Da bò dập vân cá sấu thật, khoá liền đồng thau cổ điển. Sang trọng, bền bỉ.",
    specs: [
      { label: "Chất liệu", value: "Da bò vân cá sấu" },
      { label: "Khoá", value: "Đồng thau antique" },
      { label: "Rộng", value: "35mm" },
      { label: "Bảo hành", value: "12 tháng" },
    ],
    tags: ["croc-embossed", "luxury"],
    rating: 4.7,
    reviewCount: 88,
    stock: 15,
    isLuxury: true,
  },
  {
    id: "p-belt-04",
    slug: "that-lung-hai-mat",
    name: "Thắt Lưng Hai Mặt Đen–Nâu",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 420000,
    icon: "belt",
    images: [],
    description:
      "Một chiếc thắt lưng, hai phong cách: mặt đen formal, mặt nâu casual. Khoá xoay 180°.",
    specs: [
      { label: "Chất liệu", value: "Da bò split" },
      { label: "Khoá", value: "Xoay 180°" },
      { label: "Rộng", value: "33mm" },
      { label: "Màu", value: "Đen / Nâu" },
    ],
    tags: ["reversible", "versatile"],
    rating: 4.4,
    reviewCount: 134,
    stock: 42,
  },
  {
    id: "p-belt-05",
    slug: "that-lung-braided",
    name: "Thắt Lưng Bện Tay Da Bò",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 560000,
    icon: "belt",
    images: [],
    description:
      "Bện thủ công 8 sợi da bò, co giãn linh hoạt, không cần lỗ, thoải mái cả ngày.",
    specs: [
      { label: "Chất liệu", value: "Da bò bện 8 sợi" },
      { label: "Khoá", value: "Inox bạc" },
      { label: "Rộng", value: "35mm" },
      { label: "Co giãn", value: "Có" },
    ],
    tags: ["braided", "casual"],
    rating: 4.5,
    reviewCount: 67,
    stock: 30,
  },
  {
    id: "p-belt-06",
    slug: "that-lung-montblanc-style",
    name: "Thắt Lưng Khoá Chữ M Premium",
    brand: "IRONMAN",
    categorySlug: "belts",
    categoryName: "Belts",
    price: 680000,
    icon: "belt",
    images: [],
    description:
      "Khoá chữ M mạ PVD gold, da Saffiano đen. Dòng cao cấp nhất của IRONMAN.",
    specs: [
      { label: "Chất liệu", value: "Da Saffiano" },
      { label: "Khoá", value: "PVD gold chữ M" },
      { label: "Rộng", value: "35mm" },
      { label: "Hộp", value: "Hộp gỗ + túi nhung" },
    ],
    tags: ["premium", "gift"],
    rating: 4.8,
    reviewCount: 53,
    stock: 12,
    isLuxury: true,
  },
];
