import type { CatalogProduct } from "~/types/landing";

/** Danh mục Kính Mắt — 6 sản phẩm. */
export const GLASSES_PRODUCTS: CatalogProduct[] = [
  {
    id: "p-glasses-01",
    slug: "rayban-aviator-classic",
    name: "Ray-Ban Aviator Classic RB3025",
    brand: "Ray-Ban",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 2200000,
    icon: "glasses",
    images: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Biểu tượng phi công từ 1937. Gọng vàng, tròng G-15 xanh lá. UV400, phân cực.",
    specs: [
      { label: "Gọng", value: "Kim loại vàng" },
      { label: "Tròng", value: "G-15 phân cực" },
      { label: "Chống", value: "UV400" },
      { label: "Kích cỡ", value: "58mm" },
    ],
    tags: ["aviator", "iconic"],
    rating: 4.8,
    reviewCount: 287,
    stock: 35,
    isBestSeller: true,
  },
  {
    id: "p-glasses-02",
    slug: "persol-po0649",
    name: "Persol PO0649 Steve McQueen",
    brand: "Persol",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 4800000,
    icon: "glasses",
    images: [
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Thiết kế Italy, bản lề Meflecto linh hoạt, acetate tortoise shell, tròng crystal green.",
    specs: [
      { label: "Gọng", value: "Acetate Havana" },
      { label: "Bản lề", value: "Meflecto" },
      { label: "Tròng", value: "Crystal green" },
      { label: "Xuất xứ", value: "Italy" },
    ],
    tags: ["luxury", "italian"],
    rating: 4.9,
    reviewCount: 63,
    stock: 7,
    isLuxury: true,
  },
  {
    id: "p-glasses-03",
    slug: "hugo-boss-1199s",
    name: "Hugo Boss 1199/S",
    brand: "Hugo Boss",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 3100000,
    icon: "glasses",
    images: [],
    description:
      "Gọng titanium siêu nhẹ, mặt vuông nam tính, tròng gradient smoke. Phong cách doanh nhân.",
    specs: [
      { label: "Gọng", value: "Titanium matte" },
      { label: "Tròng", value: "Gradient smoke" },
      { label: "Trọng lượng", value: "22g" },
      { label: "Kích cỡ", value: "56mm" },
    ],
    tags: ["business", "titanium"],
    rating: 4.5,
    reviewCount: 41,
    stock: 18,
    isNew: true,
  },
  {
    id: "p-glasses-04",
    slug: "oakley-holbrook",
    name: "Oakley Holbrook OO9102",
    brand: "Oakley",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 2800000,
    icon: "glasses",
    images: [],
    description:
      "O Matter frame bền nhẹ, tròng Prizm tương phản cao. Casual, thể thao, sáng tối đều đẹp.",
    specs: [
      { label: "Gọng", value: "O Matter" },
      { label: "Tròng", value: "Prizm Black" },
      { label: "Chống", value: "UV400" },
      { label: "Kích cỡ", value: "55mm" },
    ],
    tags: ["sporty", "prizm"],
    rating: 4.6,
    reviewCount: 178,
    stock: 28,
  },
  {
    id: "p-glasses-05",
    slug: "montblanc-mb0263s",
    name: "Mont Blanc MB0263S",
    brand: "Mont Blanc",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 7200000,
    icon: "glasses",
    images: [],
    description:
      "Logo snowcap trên gọng vàng hồng, acetate đen bóng, tròng xám chống lóa. Đẳng cấp thượng lưu.",
    specs: [
      { label: "Gọng", value: "Acetate + kim loại rose gold" },
      { label: "Tròng", value: "Xám polarized" },
      { label: "Xuất xứ", value: "Italy" },
      { label: "Kích cỡ", value: "54mm" },
    ],
    tags: ["luxury", "business"],
    rating: 4.9,
    reviewCount: 22,
    stock: 4,
    isLuxury: true,
  },
  {
    id: "p-glasses-06",
    slug: "rayban-wayfarer",
    name: "Ray-Ban Original Wayfarer RB2140",
    brand: "Ray-Ban",
    categorySlug: "glasses",
    categoryName: "Glasses",
    price: 2500000,
    icon: "glasses",
    images: [],
    description:
      "Huyền thoại từ 1956. Acetate đen, tròng G-15. Không bao giờ lỗi mốt.",
    specs: [
      { label: "Gọng", value: "Acetate đen" },
      { label: "Tròng", value: "G-15" },
      { label: "Chống", value: "UV400" },
      { label: "Kích cỡ", value: "50mm" },
    ],
    tags: ["wayfarer", "iconic"],
    rating: 4.7,
    reviewCount: 345,
    stock: 40,
  },
];
