import type { CatalogProduct } from "~/types/landing";

/** Danh mục Mũ — 6 sản phẩm. */
export const HAT_PRODUCTS: CatalogProduct[] = [
  {
    id: "p-hat-01",
    slug: "fedora-len-long-cuu",
    name: "Fedora Len Lông Cừu Classic",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 680000,
    icon: "hat",
    images: [
      "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Len lông cừu Úc, vành 7cm, băng grosgrain đen. Phong cách quý ông thập niên 40.",
    specs: [
      { label: "Chất liệu", value: "Len lông cừu 100%" },
      { label: "Vành", value: "7cm" },
      { label: "Size", value: "M/L/XL" },
      { label: "Màu", value: "Đen / Xám / Nâu" },
    ],
    tags: ["fedora", "classic", "wool"],
    rating: 4.7,
    reviewCount: 56,
    stock: 20,
    isBestSeller: true,
  },
  {
    id: "p-hat-02",
    slug: "flat-cap-tweed",
    name: "Flat Cap Tweed Harris",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 520000,
    icon: "hat",
    images: [
      "https://images.unsplash.com/photo-1588850561407-ed78c334e67a?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Vải tweed Harris Scotland, lót lụa, lưỡi trai cứng. Mũ beret Anh cổ điển.",
    specs: [
      { label: "Chất liệu", value: "Harris Tweed" },
      { label: "Lót", value: "Lụa" },
      { label: "Size", value: "M/L/XL" },
      { label: "Xuất xứ vải", value: "Scotland" },
    ],
    tags: ["flat-cap", "tweed", "british"],
    rating: 4.6,
    reviewCount: 43,
    stock: 18,
    isNew: true,
  },
  {
    id: "p-hat-03",
    slug: "beret-da-nappa",
    name: "Beret Da Nappa Đen",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 750000,
    icon: "hat",
    images: [],
    description:
      "Da nappa cừu mềm mịn, lót cotton thoáng, kiểu dáng beret Pháp. Sang trọng bốn mùa.",
    specs: [
      { label: "Chất liệu", value: "Da nappa cừu" },
      { label: "Lót", value: "Cotton" },
      { label: "Size", value: "M/L/XL" },
      { label: "Màu", value: "Đen" },
    ],
    tags: ["beret", "leather", "french"],
    rating: 4.8,
    reviewCount: 31,
    stock: 10,
    isLuxury: true,
  },
  {
    id: "p-hat-04",
    slug: "panama-coi-thu-cong",
    name: "Mũ Panama Cói Ecuador",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 1200000,
    icon: "hat",
    images: [],
    description:
      "Cói Toquilla bện thủ công tại Ecuador. Nhẹ, thoáng, gập được. Biểu tượng mùa hè quý ông.",
    specs: [
      { label: "Chất liệu", value: "Cói Toquilla" },
      { label: "Bện", value: "Thủ công" },
      { label: "Vành", value: "6.5cm" },
      { label: "Xuất xứ", value: "Ecuador" },
    ],
    tags: ["panama", "handmade", "summer"],
    rating: 4.9,
    reviewCount: 19,
    stock: 6,
    isLuxury: true,
  },
  {
    id: "p-hat-05",
    slug: "mu-newsboy-wool",
    name: "Newsboy Cap Wool Blend",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 450000,
    icon: "hat",
    images: [],
    description:
      "Mũ newsboy 8 múi, len pha, nút bọc trên đỉnh. Phong cách Peaky Blinders.",
    specs: [
      { label: "Chất liệu", value: "Len pha 80/20" },
      { label: "Kiểu", value: "8 múi" },
      { label: "Size", value: "M/L/XL" },
      { label: "Màu", value: "Xám đậm" },
    ],
    tags: ["newsboy", "peaky-blinders"],
    rating: 4.5,
    reviewCount: 67,
    stock: 25,
    isBestSeller: true,
  },
  {
    id: "p-hat-06",
    slug: "mu-bucket-da-lon",
    name: "Bucket Hat Da Lộn",
    brand: "IRONMAN",
    categorySlug: "hats",
    categoryName: "Hats",
    price: 580000,
    icon: "hat",
    images: [],
    description:
      "Da lộn (suede) mềm mại, vành ngắn 5cm, kiểu dáng bucket hiện đại. Casual sang trọng.",
    specs: [
      { label: "Chất liệu", value: "Da lộn (suede)" },
      { label: "Vành", value: "5cm" },
      { label: "Size", value: "M/L" },
      { label: "Màu", value: "Nâu camel" },
    ],
    tags: ["bucket", "suede", "casual"],
    rating: 4.4,
    reviewCount: 38,
    stock: 22,
    isNew: true,
  },
];
