import type { CatalogProduct } from "~/types/landing";

/** Danh mục Ví Da — 6 sản phẩm. */
export const WALLET_PRODUCTS: CatalogProduct[] = [
  {
    id: "p-wallet-01",
    slug: "vi-bifold-italy",
    name: "Ví Bifold Da Bò Italy",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 850000,
    icon: "wallet",
    images: [
      "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Da bò Italy vegetable-tanned, 8 ngăn thẻ, 2 ngăn tiền, 1 ngăn zip. Lên patina đẹp theo thời gian.",
    specs: [
      { label: "Chất liệu", value: "Veg-tan Italy" },
      { label: "Ngăn thẻ", value: "8" },
      { label: "Kích thước", value: "11×9.5cm" },
      { label: "Màu", value: "Nâu cognac" },
    ],
    tags: ["bifold", "classic"],
    rating: 4.7,
    reviewCount: 189,
    stock: 35,
    isBestSeller: true,
  },
  {
    id: "p-wallet-02",
    slug: "vi-card-holder",
    name: "Card Holder Da Saffiano",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 350000,
    icon: "wallet",
    images: [],
    description:
      "6 ngăn thẻ, 1 ngăn giữa. Da Saffiano chống trầy, mỏng gọn bỏ túi trước.",
    specs: [
      { label: "Chất liệu", value: "Da Saffiano" },
      { label: "Ngăn thẻ", value: "6" },
      { label: "Kích thước", value: "10×7.5cm" },
      { label: "Độ dày", value: "7mm" },
    ],
    tags: ["card-holder", "slim"],
    rating: 4.5,
    reviewCount: 234,
    stock: 65,
    isNew: true,
  },
  {
    id: "p-wallet-03",
    slug: "vi-dai-da-bo",
    name: "Ví Dài Da Bò Zipper",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 980000,
    icon: "wallet",
    images: [],
    description:
      "Ví dài full-zip, 12 ngăn thẻ, 3 ngăn tiền, 1 ngăn phone. Da bò nappa mềm mịn.",
    specs: [
      { label: "Chất liệu", value: "Da nappa" },
      { label: "Ngăn thẻ", value: "12" },
      { label: "Kích thước", value: "20×10cm" },
      { label: "Khóa", value: "YKK zipper" },
    ],
    tags: ["long-wallet", "zipper"],
    rating: 4.6,
    reviewCount: 97,
    stock: 20,
    isLuxury: true,
  },
  {
    id: "p-wallet-04",
    slug: "vi-money-clip",
    name: "Money Clip Da + Thép",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 450000,
    icon: "wallet",
    images: [],
    description:
      "Kẹp tiền thép phay CNC, bọc da bò hai mặt. 4 ngăn thẻ. Mỏng chỉ 8mm.",
    specs: [
      { label: "Chất liệu", value: "Da bò + thép 316L" },
      { label: "Ngăn thẻ", value: "4" },
      { label: "Kích thước", value: "10.5×7.5cm" },
      { label: "Độ dày", value: "8mm" },
    ],
    tags: ["money-clip", "minimalist"],
    rating: 4.4,
    reviewCount: 78,
    stock: 38,
  },
  {
    id: "p-wallet-05",
    slug: "vi-passport-da",
    name: "Ví Passport Da Bò",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 520000,
    icon: "wallet",
    images: [],
    description:
      "Ngăn passport, 4 ngăn thẻ, ngăn boarding pass. Khắc tên miễn phí — quà đi du lịch lý tưởng.",
    specs: [
      { label: "Chất liệu", value: "Da bò full-grain" },
      { label: "Ngăn", value: "Passport + 4 thẻ" },
      { label: "Kích thước", value: "14×10cm" },
      { label: "Khắc tên", value: "Miễn phí" },
    ],
    tags: ["passport", "travel", "gift"],
    rating: 4.8,
    reviewCount: 112,
    stock: 25,
    isBestSeller: true,
  },
  {
    id: "p-wallet-06",
    slug: "vi-rfid-blocking",
    name: "Ví RFID Blocking Slim",
    brand: "IRONMAN",
    categorySlug: "wallets",
    categoryName: "Wallets",
    price: 620000,
    icon: "wallet",
    images: [],
    description:
      "Lớp chống RFID bảo vệ thẻ. Da carbon fiber texture, 6 ngăn thẻ, ngăn tiền mặt.",
    specs: [
      { label: "Chất liệu", value: "Da carbon texture" },
      { label: "RFID", value: "Blocking" },
      { label: "Ngăn thẻ", value: "6" },
      { label: "Độ dày", value: "10mm" },
    ],
    tags: ["rfid", "tech", "slim"],
    rating: 4.5,
    reviewCount: 89,
    stock: 30,
    isNew: true,
  },
];
