import type { CatalogProduct } from "~/types/landing";

/**
 * Danh mục Đồng Hồ — 17 sản phẩm theo bảng giá nhập/bán nội bộ.
 * - `price`   = Giá Bán
 * - `salePrice` (khi có) = Giá nhập (hiển thị như mức ưu đãi tham chiếu)
 */
export const WATCH_PRODUCTS: CatalogProduct[] = [
  {
    id: "p-watch-01",
    slug: "seiko-5-xanh-la",
    name: "Seiko 5 Xanh Lá",
    brand: "Seiko",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/senko-green-1.jpg",
      "/watch/senko-green-2.jpg",
      "/watch/senko-green-3.jpg",
      "/watch/senko-green-4.jpg",
      "/watch/senko-green-5.jpg",
    ],
    description:
      "Đồng hồ Seiko 5 mặt số xanh lá tươi, dây kim loại bạc, bộ máy automatic.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "40mm" },
      { label: "Dây", value: "Kim loại" },
    ],
    tags: ["seiko", "automatic", "xanh-la"],
    rating: 4.5,
    reviewCount: 50,
    stock: 20,
  },
  {
    id: "p-watch-02",
    slug: "thuy-quan-luc-chien-do",
    name: "Thủy Quân Lục Chiến Đỏ",
    brand: "Marine",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/marine-corps-1.jpg",
      "/watch/marine-corps-2.jpg",
      "/watch/marine-corps-3.jpg",
      "/watch/marine-corps-4.jpg",
      "/watch/marine-corps-5.jpg",
    ],
    description:
      "Đồng hồ phong cách quân đội, mặt số đỏ nổi bật, dây vải dù chắc chắn.",
    specs: [
      { label: "Bộ máy", value: "Quartz" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "42mm" },
      { label: "Dây", value: "Vải dù" },
    ],
    tags: ["military", "do", "sporty"],
    rating: 4.4,
    reviewCount: 40,
    stock: 25,
  },
  {
    id: "p-watch-03",
    slug: "omega-kham-trai",
    name: "Omega Khảm Trai",
    brand: "Omega",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/omg-white-1.jpg",
      "/watch/omg-white-2.jpg",
      "/watch/omg-white-3.jpg",
      "/watch/omg-white-4.jpg",
    ],
    description:
      "Mặt số khảm trai óng ánh tự nhiên, gọng vàng sang trọng, kiểu Omega cổ điển.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "40mm" },
      { label: "Mặt", value: "Khảm trai" },
    ],
    tags: ["omega", "kham-trai", "sang-trong"],
    rating: 4.6,
    reviewCount: 55,
    stock: 18,
  },
  {
    id: "p-watch-04",
    slug: "omega-lua-trang",
    name: "Omega Lụa Trắng",
    brand: "Omega",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 152_000,
    icon: "watch",
    images: [
      "/watch/omg-luatrang-1.jpg",
      "/watch/omg-luatrang-2.jpg",
      "/watch/omg-luatrang-3.jpg",
      "/watch/omg-luatrang-4.jpg",
    ],
    description:
      "Đồng hồ Omega mặt trắng lụa thanh lịch, dây da mềm, phù hợp công sở.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "40mm" },
      { label: "Dây", value: "Da" },
    ],
    tags: ["omega", "trang", "thanh-lich"],
    rating: 4.5,
    reviewCount: 48,
    stock: 22,
  },
  {
    id: "p-watch-05",
    slug: "patek-lua-vang",
    name: "Patek Lụa Vàng",
    brand: "Patek Philippe",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 152_000,
    icon: "watch",
    images: [
      "/watch/patex-luavang-1.jpg",
      "/watch/patex-luavang-2.jpg",
      "/watch/patex-luavang-3.jpg",
      "/watch/patex-luavang-4.jpg",
    ],
    description:
      "Phong cách Patek mặt vàng lụa quý phái, vỏ mạ gold, dây da nâu lịch lãm.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "40mm" },
      { label: "Dây", value: "Da nâu" },
    ],
    tags: ["patek", "vang", "luxury"],
    rating: 4.7,
    reviewCount: 62,
    stock: 15,
    isLuxury: true,
  },
  {
    id: "p-watch-06",
    slug: "orient-chem-canh-do-day-trang",
    name: "Orient Chém Cạnh Đỏ Dây Trắng",
    brand: "Orient",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/oren-1.PNG",
      "/watch/oren-2.PNG",
      "/watch/oren-3.PNG",
      "/watch/oren-4.PNG",
    ],
    description:
      "Orient mặt đỏ chém cạnh sắc nét, dây thép sơn trắng, cá tính trẻ trung.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "41mm" },
      { label: "Dây", value: "Thép sơn trắng" },
    ],
    tags: ["orient", "do", "chem-canh"],
    rating: 4.4,
    reviewCount: 38,
    stock: 20,
  },
  {
    id: "p-watch-07",
    slug: "rolex-do",
    name: "Rolex Đỏ",
    brand: "Rolex",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 280_000,
    salePrice: 145_000,
    icon: "watch",
    images: [
      "https://i.pinimg.com/736x/7e/f0/43/7ef043e51ced476d5a8d7d09b320fe75.jpg",
      "https://i.pinimg.com/736x/81/6c/6e/816c6e12077d63eceb0734466c4c32ee.jpg",
      "https://i.pinimg.com/1200x/46/ac/7d/46ac7d3bfb14df3c284aafe22dddeb78.jpg"
    ],
    description:
      "Phong cách Rolex Submariner mặt đỏ rực, dây kim loại đặc, bộ máy automatic.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "5ATM" },
      { label: "Đường kính", value: "41mm" },
      { label: "Dây", value: "Kim loại" },
    ],
    tags: ["rolex", "do", "luxury"],
    rating: 4.8,
    reviewCount: 80,
    stock: 12,
    isBestSeller: true,
    isLuxury: true,
  },
  {
    id: "p-watch-08",
    slug: "orient-vuong-vang",
    name: "Orient Vuông Vàng",
    brand: "Orient",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/oren-yellow-1.jpg",
      "/watch/oren-yellow-2.jpg",
      "/watch/oren-yellow-3.jpg",
      "/watch/oren-yellow-4.jpg",
    ],
    description:
      "Orient mặt vuông vàng cổ điển, kiểu dáng dress-watch tinh tế cho doanh nhân.",
    specs: [
      { label: "Bộ máy", value: "Quartz" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Kích thước", value: "36mm vuông" },
      { label: "Dây", value: "Kim loại mạ vàng" },
    ],
    tags: ["orient", "vuong", "vang"],
    rating: 4.5,
    reviewCount: 42,
    stock: 18,
  },
  {
    id: "p-watch-09",
    slug: "omega-thuyen-buom-day-lua",
    name: "Omega Thuyền Buồm Dây Lụa",
    brand: "Omega",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/omg-sailboat-1.jpg",
      "/watch/omg-sailboat-2.jpg",
      "/watch/omg-sailboat-3.jpg",
      "/watch/omg-sailboat-4.jpg",
    ],
    description:
      "Mặt số họa tiết thuyền buồm lãng tử, dây lụa nhẹ êm tay, sang trọng khác biệt.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "40mm" },
      { label: "Dây", value: "Lụa" },
    ],
    tags: ["omega", "thuyen-buom", "day-lua"],
    rating: 4.6,
    reviewCount: 47,
    stock: 16,
  },
  {
    id: "p-watch-10",
    slug: "orient-3-sao-do-xanh-la",
    name: "Orient 3 Sao Đỏ + Xanh Lá",
    brand: "Orient",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 152_000,
    icon: "watch",
    images: [
      "/watch/orient-3-star-1.jpg",
      "/watch/orient-3-star-2.jpg",
      "/watch/orient-3-star-3.jpg",
      "/watch/orient-3-star-4.jpg",
      "/watch/orient-3-star-5.jpg",
    ],
    description:
      "Orient 3 sao mặt số kết hợp đỏ và xanh lá tương phản mạnh, phong cách thể thao.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "41mm" },
      { label: "Dây", value: "Kim loại" },
    ],
    tags: ["orient", "3-sao", "sporty"],
    rating: 4.4,
    reviewCount: 36,
    stock: 22,
  },
  {
    id: "p-watch-11",
    slug: "rado-vang-dam",
    name: "Rado Vàng Đậm",
    brand: "Rado",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 285_000,
    salePrice: 150_000,
    icon: "watch",
    images: [
      "/watch/rado-bold-1.jpg",
      "/watch/rado-bold-2.jpg",
      "/watch/rado-bold-3.jpg",
      "/watch/rado-bold-4.jpg",
    ],
    description:
      "Rado vỏ và mặt số vàng đậm, vẻ sang quý cổ điển, dây kim loại mạ vàng.",
    specs: [
      { label: "Bộ máy", value: "Quartz" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "39mm" },
      { label: "Dây", value: "Kim loại mạ vàng" },
    ],
    tags: ["rado", "vang", "classic"],
    rating: 4.5,
    reviewCount: 44,
    stock: 18,
  },
  {
    id: "p-watch-12",
    slug: "seiko-nau",
    name: "Seiko Nâu",
    brand: "Seiko",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/senko-brown-1.jpg",
      "/watch/senko-brown-2.PNG",
      "/watch/senko-brown-3.PNG",
      "/watch/senko-brown-4.PNG",
    ],
    description:
      "Seiko mặt nâu trầm ấm, dây da bò nâu cùng tông, lựa chọn an toàn cho mọi outfit.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "40mm" },
      { label: "Dây", value: "Da nâu" },
    ],
    tags: ["seiko", "nau", "daily"],
    rating: 4.5,
    reviewCount: 52,
    stock: 24,
  },
  {
    id: "p-watch-13",
    slug: "sk-mat-lua",
    name: "SK Mặt Lửa",
    brand: "SK",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 280_000,
    salePrice: 147_000,
    icon: "watch",
    images: [
      "/watch/sk-fire-1.jpg",
      "/watch/sk-fire-2.jpg",
      "/watch/sk-fire-3.jpg",
    ],
    description:
      "SK mặt số hiệu ứng lửa cam–đỏ độc đáo, vỏ thép đen, phong cách trẻ trung mạnh mẽ.",
    specs: [
      { label: "Bộ máy", value: "Quartz" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "42mm" },
      { label: "Dây", value: "Thép đen" },
    ],
    tags: ["sk", "mat-lua", "sporty"],
    rating: 4.3,
    reviewCount: 30,
    stock: 25,
    isNew: true,
  },
  {
    id: "p-watch-14",
    slug: "orient-chem-canh-full-vang",
    name: "Orient Chém Cạnh Full Vàng",
    brand: "Orient",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/oren-full-yellow-1.PNG",
      "/watch/oren-full-yellow-2.PNG",
      "/watch/oren-full-yellow-3.PNG",
      "/watch/oren-full-yellow-4.PNG",
    ],
    description:
      "Orient chém cạnh full vàng, dây và mặt đồng bộ, lựa chọn nổi bật cho buổi tiệc.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "41mm" },
      { label: "Dây", value: "Kim loại mạ vàng" },
    ],
    tags: ["orient", "vang", "chem-canh"],
    rating: 4.5,
    reviewCount: 41,
    stock: 16,
  },
  {
    id: "p-watch-15",
    slug: "orient-chem-canh-mat-do-day-vang",
    name: "Orient Chém Cạnh Mặt Đỏ Dây Vàng",
    brand: "Orient",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/oren-cc-red-1.jpg",
      "/watch/oren-cc-red-2.jpg",
      "/watch/oren-cc-red-3.jpg",
    ],
    description:
      "Orient chém cạnh tương phản: mặt đỏ rực trên dây vàng bóng, cá tính ấn tượng.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "41mm" },
      { label: "Dây", value: "Kim loại mạ vàng" },
    ],
    tags: ["orient", "do", "vang"],
    rating: 4.5,
    reviewCount: 39,
    stock: 18,
  },
  {
    id: "p-watch-16",
    slug: "omega-rang-ca-map",
    name: "Omega Răng Cá Mập",
    brand: "Omega",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/omg-shark-1.jpg",
      "/watch/omg-shark-2.jpg",
      "/watch/omg-shark-3.jpg",
      "/watch/omg-shark-4.jpg",
    ],
    description:
      "Omega kiểu dáng đặc biệt với viền bezel răng cá mập sắc nét, mạnh mẽ và độc đáo.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "5ATM" },
      { label: "Đường kính", value: "42mm" },
      { label: "Dây", value: "Kim loại" },
    ],
    tags: ["omega", "rang-ca-map", "doc-dao"],
    rating: 4.7,
    reviewCount: 58,
    stock: 14,
    isBestSeller: true,
  },
  {
    id: "p-watch-17",
    slug: "seiko-5-mat-do-day-vang",
    name: "Seiko 5 Mặt Đỏ Dây Vàng",
    brand: "Seiko",
    categorySlug: "watches",
    categoryName: "Watches",
    price: 300_000,
    salePrice: 155_000,
    icon: "watch",
    images: [
      "/watch/senko-red-yellow-1.jpg",
      "/watch/senko-red-yellow-2.jpg",
    ],
    description:
      "Seiko 5 mặt đỏ rực kết hợp dây kim loại mạ vàng, dòng cổ điển luôn được ưa chuộng.",
    specs: [
      { label: "Bộ máy", value: "Automatic" },
      { label: "Chống nước", value: "3ATM" },
      { label: "Đường kính", value: "40mm" },
      { label: "Dây", value: "Kim loại mạ vàng" },
    ],
    tags: ["seiko", "do", "vang"],
    rating: 4.6,
    reviewCount: 49,
    stock: 20,
    isNew: true,
  },
];
