import type { CatalogProduct } from "~/types/landing";

/** Danh mục Zippo — 6 sản phẩm. */
export const ZIPPO_PRODUCTS: CatalogProduct[] = [
  {
    id: "p-zippo-01",
    slug: "zippo-black-ice",
    name: "Zippo Black Ice 150",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 650000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/1200x/72/b8/f7/72b8f76799dc6e82f50b09aa91e69cdf.jpg",
    ],
    description:
      "Lớp phủ Black Ice phản chiếu bóng loáng như gương đen. Khắc tên laser miễn phí.",
    specs: [
      { label: "Chất liệu", value: "Đồng thau mạ PVD" },
      { label: "Kích thước", value: "56×36×12mm" },
      { label: "Xuất xứ", value: "Bradford, PA, USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["classic", "black"],
    rating: 4.7,
    reviewCount: 312,
    stock: 45,
    isBestSeller: true,
  },
  {
    id: "p-zippo-02",
    slug: "zippo-armor-deep-carve",
    name: "Zippo Armor Deep Carve",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 1350000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/736x/0f/49/d2/0f49d26cfb9f2240619adb8814872fca.jpg",
    ],
    description:
      "Vỏ Armor dày 1.5x, khắc chìm 360° hoa văn Celtic. Mạ antique brass.",
    specs: [
      { label: "Chất liệu", value: "Đồng Armor 1.5x" },
      { label: "Kỹ thuật", value: "Deep carve 360°" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["armor", "limited"],
    rating: 4.9,
    reviewCount: 56,
    stock: 8,
    isLuxury: true,
  },
  {
    id: "p-zippo-03",
    slug: "zippo-venetian-brass",
    name: "Zippo Venetian High Polish Brass",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 780000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/webp80/736x/8c/0f/92/8c0f92c1ff7913f0899678c2d212fe17.webp",
    ],
    description:
      "Họa tiết Venetian cổ điển khắc hai mặt, đồng thau bóng cao. Biểu tượng Zippo vượt thời gian.",
    specs: [
      { label: "Chất liệu", value: "Đồng thau bóng" },
      { label: "Họa tiết", value: "Venetian hai mặt" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["vintage", "brass"],
    rating: 4.6,
    reviewCount: 98,
    stock: 25,
  },
  {
    id: "p-zippo-04",
    slug: "zippo-matte-navy",
    name: "Zippo Navy Matte 239",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 550000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/736x/ba/60/3f/ba603fc7eeb31b65c935eb6b35cc6e19.jpg",
    ],
    description:
      "Bề mặt sơn matte xanh navy trầm lắng. Mặc định cho gentleman — không phô trương, đủ tinh tế.",
    specs: [
      { label: "Chất liệu", value: "Thép sơn matte" },
      { label: "Màu", value: "Navy #239" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["matte", "everyday"],
    rating: 4.3,
    reviewCount: 145,
    stock: 60,
    isNew: true,
  },
  {
    id: "p-zippo-05",
    slug: "zippo-replica-1941",
    name: "Zippo 1941 Replica Brushed Chrome",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 890000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/736x/34/33/39/343339fcf3e40d20097689d1d81281bb.jpg",
    ],
    description:
      "Phiên bản tái hiện mẫu 1941 — góc bo tròn, bản lề 4 trục, vỏ thép chrome brushed.",
    specs: [
      { label: "Chất liệu", value: "Thép chrome" },
      { label: "Dòng", value: "1941 Replica" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["replica", "heritage"],
    rating: 4.8,
    reviewCount: 76,
    stock: 14,
    isLuxury: true,
  },
  {
    id: "p-zippo-06",
    slug: "zippo-jack-daniels",
    name: "Zippo Jack Daniel's Old No. 7",
    brand: "Zippo",
    categorySlug: "zippo",
    categoryName: "Zippo",
    price: 950000,
    icon: "zippo",
    images: [
      "https://i.pinimg.com/736x/3d/ea/57/3dea57bf61d87893f4cca0aa535faf34.jpg",
    ],
    description:
      "Phiên bản hợp tác Jack Daniel's, khắc logo nổi trên nền thép đen matte.",
    specs: [
      { label: "Chất liệu", value: "Thép đen matte" },
      { label: "Phiên bản", value: "Jack Daniel's collab" },
      { label: "Xuất xứ", value: "USA" },
      { label: "Bảo hành", value: "Trọn đời" },
    ],
    tags: ["collab", "limited"],
    rating: 4.7,
    reviewCount: 42,
    stock: 10,
    isBestSeller: true,
  },
];
